Transform: AWS::Serverless-2016-10-31
Description: AWS Resources for the Minecraft server

Mappings:
  Global:
    EC2:
      AvailabilityZone: us-east-1a
      InstanceType: t2.medium

    Lambda:
      Runtime: python3.12
      Architecture: arm64
      LogLevel: INFO
      ServerPeriod: 4

Parameters:
  Owner:
    Type: String
    Default: jack

  Project:
    Type: String
    Default: Minecraft

  AppName:
    Type: String
    Default: Minecraft

  HostedZone:
    Type: String
    Default: Z0922428ZJ5CNMUTNWOR
  
  DomainName:
    Type: String
    Default: curranserver.click
    AllowedPattern: ^[\w+\.]+\w+$

  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:298451523862:certificate/0dba9e39-fee9-483e-8794-cf240efff79e

  ContactEmail:
    Type: String
    Default: jackcurran49@gmail.com
    AllowedPattern: ^\w+@\w+\.\w+$

  SourceBucket:
    Type: String
    Default: minecraft-world-curran
    AllowedPattern: ^\w+[\w+\-\w+]*$

Resources:
  # IAM
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      RoleName: !Sub Lambda-${AppName}
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  ServerHostIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      RoleName: !Sub EC2Role-${AppName}
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  SchedulerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      RoleName: !Sub EventBridge-${AppName}
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  ServerHostInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub EC2Role-${AppName}
      Roles:
        - !Ref ServerHostIAMRole

  # EC2
  ServerHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows access to the server only through the Minecraft portal.
      GroupName: !Sub ${AppName} SG
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allows access everywhere with no limitations
          FromPort: -1
          ToPort: -1
          IpProtocol: all
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allows SSH access
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          Description: Allows access from the Minecraft launcher
          FromPort: 25565
          ToPort: 25565
          IpProtocol: tcp
      Tags:
        - Key: Name
          Value: !Sub ${AppName} SG
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
      VpcId: vpc-04235c526004ddbb5

  ServerHostInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap [Global, EC2, AvailabilityZone]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            Iops: 3000
            VolumeSize: 8
            VolumeType: gp3
      IamInstanceProfile: !Ref ServerHostInstanceProfile
      ImageId: ami-08a0d1e16fc3f61ea
      InstanceType: !FindInMap [Global, EC2, InstanceType]
      SecurityGroupIds:
        - !GetAtt ServerHostSecurityGroup.GroupId
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            
            set +e

            sudo yum update -y
            sudo yum install -y java-21-amazon-corretto-headless
            sudo yum install -y https://s3.${AWS::Region}.amazonaws.com/amazon-ssm-${AWS::Region}/latest/linux_amd64/amazon-ssm-agent.rpm

            wget https://amazoncloudwatch-agent-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
            sudo rpm -U amazon-cloudwatch-agent.rpm
            sudo aws s3 cp s3://minecraft-world-curran/logs/config.json /opt/aws/amazon-cloudwatch-agent/bin/config.json
            sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s

            sudo mkdir /opt/minecraft
            cd /opt/minecraft
            sudo aws s3 sync s3://${SourceBucket}/scripts .
            
            sudo mkdir server
            cd server
            sudo aws s3 cp s3://${SourceBucket}/server.jar server.jar
            sudo java -Xmx1024M -Xms1024M -jar server.jar nogui
            sudo aws s3 cp s3://${SourceBucket}/eula.txt eula.txt
            sudo aws s3 cp s3://${SourceBucket}/server.properties server.properties
            sudo java -Xmx1024M -Xms1024M -jar server.jar nogui
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-Server
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  # Lambda
  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - arm64
        - x86_64
      CompatibleRuntimes:
        - !FindInMap [Global, Lambda, Runtime]
      ContentUri: ./layer
      LayerName: !Sub ${AppName}-dependencies
      RetentionPolicy: Delete

  APILambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - !FindInMap [Global, Lambda, Architecture]
      CodeUri: ./lambda/api
      Description: Manages the Minecraft server
      Environment:
        Variables:
          INSTANCE_ID: !Ref ServerHostInstance
          DOMAIN: !Ref DomainName
          REGION: !Ref AWS::Region
          PERIOD: !FindInMap [Global, Lambda, ServerPeriod]
          STARTUP_FUNCTION: !Ref StartupLambda
          SNS_TOPIC: !Ref SNSAlertTopic
          POWERTOOLS_SERVICE_NAME: !Ref AppName
          POWERTOOLS_LOG_LEVEL: !FindInMap [Global, Lambda, LogLevel]
      FunctionName: !Ref AppName
      Handler: app.handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MinecraftAPI
            Method: ANY
            Path: /{path+}
            PayloadFormatVersion: "2.0"
      Layers:
        - !Ref DependencyLayer
      MemorySize: 128
      Runtime: !FindInMap [Global, Lambda, Runtime]
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  StartupLambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - !FindInMap [Global, Lambda, Architecture]
      CodeUri: ./lambda/startup
      Description: Updates the Route53 record when server starts
      Environment:
        Variables:
          INSTANCE_ID: !Ref ServerHostInstance
          DOMAIN: !Ref DomainName
          REGION: !Ref AWS::Region
          HOSTED_ZONE_ID: !Ref HostedZone
          POWERTOOLS_SERVICE_NAME: !Sub ${AppName}-Startup
          POWERTOOLS_LOG_LEVEL: !FindInMap [Global, Lambda, LogLevel]
      FunctionName: !Sub ${AppName}-Startup
      Handler: app.handler
      Layers:
        - !Ref DependencyLayer
      MemorySize: 128
      Runtime: !FindInMap [Global, Lambda, Runtime]
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  # API Gateway
  MinecraftAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: Triggers the Lambda that manages the Minecraft server
      Name: !Sub ${AppName}-API
      ProtocolType: HTTP
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  MinecraftAPIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref MinecraftAPI
      AutoDeploy: true
      StageName: $default
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  MinecraftAPIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MinecraftAPI
      Description: Integrating the Minecraft API with the managing lambda
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ""
        - - "arn:"
          - !Ref AWS::Partition
          - ":apigateway:"
          - !Ref AWS::Region
          - ":lambda:path/2015-03-31/functions/"
          - !GetAtt APILambda.Arn
          - /invocations
      PayloadFormatVersion: "2.0"

  MinecraftAPIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MinecraftAPI
      AuthorizationType: NONE
      RouteKey: ANY /{path+}
      Target: !Join
        - /
        - - integrations
          - !Ref MinecraftAPIIntegration

  MinecraftAPIDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Sub api.${DomainName}
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArn
          CertificateName: !Sub ${AppName}-APICertificate
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  MinecraftAPIDomainNameMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref MinecraftAPI
      DomainName: !Ref MinecraftAPIDomainName
      Stage: !Ref MinecraftAPIStage

  # SNS
  SNSAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${AppName}-SNS
      TopicName: !Sub ${AppName}-SNS
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  SNSAlertTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref ContactEmail
      Protocol: email
      TopicArn: !Ref SNSAlertTopic

  # Route 53
  APIRouteRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt MinecraftAPIDomainName.RegionalDomainName
        HostedZoneId: !GetAtt MinecraftAPIDomainName.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZone
      Name: !Sub api.${DomainName}
      Type: A

  # EventBridge
  ServerStatusScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Shuts down the server if it has been running for too long
      FlexibleTimeWindow:
        MaximumWindowInMinutes: 5
        Mode: "FLEXIBLE"
      Name: !Sub ${AppName}-server-monitor
      ScheduleExpression: rate(15 minutes)
      State: ENABLED
      Target:
        Arn: !GetAtt APILambda.Arn
        Input: | 
          {
            "version": "2.0",
            "routeKey": "ANY /{path+}",
            "rawPath": "/status",
            "rawQueryString": "expire=true",
            "headers": {
              "accept": "*/*",
              "accept-encoding": "gzip, deflate, br",
              "content-length": "0"
            },
            "queryStringParameters": {
              "expire": "true"
            },
            "requestContext": {
              "http": {
                "method": "GET",
                "path": "/status",
                "protocol": "HTTP/1.1"
              },
              "routeKey": "ANY /{path+}",
              "stage": "$default"
            },
            "pathParameters": {
              "path": "status"
            },
            "isBase64Encoded": false
          }
        RoleArn: !GetAtt SchedulerExecutionRole.Arn
